SELECT CURRENT_DATE FROM DUAL;

SELECT EXTRACT(YEAR FROM SYSDATE()) FROM DUAL;
SELECT EXTRACT(DAY FROM SYSDATE()) FROM DUAL;

SELECT EXTRACT(MONTH FROM SYSDATE()) FROM DUAL;
SELECT SYSDATE() FROM DUAL;

SELECT ASCII('a') FROM DUAL;
SELECT ASCII('A') FROM DUAL;

SELECT ASCII('Z') FROM DUAL;

SELECT ASCII('z') FROM DUAL;

SELECT UPPER('bldeasb arts and kcp science college') FROM DUAL;

SELECT LOWER('WELCOME TO DBMSLAB') FROM DUAL;

SELECT REPLACE('HELLO', 'H', 'K') FROM DUAL;

SELECT REPLACE('COMPUTER', 'C', 'K') FROM DUAL;
SELECT REPLACE('HELLO', 'L', 'A') FROM DUAL;

SELECT TRIM('A' FROM 'ANACONDA') FROM DUAL;

SELECT LTRIM('ANACONDA') FROM DUAL;

SELECT LTRIM('ANIL') FROM DUAL;

SELECT RTRIM('ANITA') FROM DUAL;